package base

import (
	dbSports "github.com/playback-sports/db/pkg/sports"
)

var BroadcastNameMap = map[string]dbSports.Network{
	"ABC":                   dbSports.ABC,
	"ACC Network":           dbSports.ACCNetwork,
	"ACC Network Extra":     dbSports.ACCNX,
	"ALT":                   dbSports.ALT,
	"ALT2":                  dbSports.ALT2,
	"Amazon Prime Video":    dbSports.PrimeVideo,
	"Apple TV+":             dbSports.AppleTVPlus,
	"Atlantic East Network": dbSports.AtlanticEastNetwork,
	"Barstool Sports":       dbSports.BarstoolSports,
	"B1G+":                  dbSports.B1GPlus,
	"BSAZ":                  dbSports.BSAZ,
	"BSAZ+":                 dbSports.BSAZPlus,
	"BSAZX":                 dbSports.BSAZX,
	"BSDET":                 dbSports.BSDET,
	"BSDET+":                dbSports.BSDETPlus,
	"BSDETX":                dbSports.BSDETX,
	"BSFL":                  dbSports.BSFL,
	"BSFLX":                 dbSports.BSFLX,
	"BSGL":                  dbSports.BSGL,
	"BSIN":                  dbSports.BSIN,
	"BSKC":                  dbSports.BSKC,
	"BSMW":                  dbSports.BSMW,
	"BSMWX":                 dbSports.BSMWX,
	"BSN":                   dbSports.BSN,
	"BSN+":                  dbSports.BSNPlus,
	"BSNX":                  dbSports.BSNX,
	"BSNO":                  dbSports.BSNO,
	"BSOH":                  dbSports.BSOH,
	"BSOK":                  dbSports.BSOK,
	"BSSC":                  dbSports.BSSC,
	"BSSD":                  dbSports.BSSD,
	"BSSE":                  dbSports.BSSE,
	"BSSEX":                 dbSports.BSSEX,
	"BSSO":                  dbSports.BSSO,
	"BSSUN":                 dbSports.BSSUN,
	"BSSUNX":                dbSports.BSSUNX,
	"BSSW":                  dbSports.BSSW,
	"BSSW+":                 dbSports.BSSWPlus,
	"BSSWX":                 dbSports.BSSWX,
	"BSW":                   dbSports.BSW,
	"BSWI":                  dbSports.BSWI,
	"BSWI+":                 dbSports.BSWIPlus,
	"BSWIX":                 dbSports.BSWIX,
	"BTN":                   dbSports.BTN,
	"BYUtv":                 dbSports.BYUtv,
	"CBC":                   dbSports.CBC,
	"CITY":                  dbSports.CITY,
	"CUSA TV":               dbSports.CUSATV,
	"CW-23":                 dbSports.CW23,
	"CW35":                  dbSports.CW35,
	"CBS Sports Network":    dbSports.CBSSportsNetwork,
	"CBS":                   dbSports.CBS,
	"ESPN":                  dbSports.ESPN,
	"ESPN+":                 dbSports.ESPNPlus,
	"ESPN2":                 dbSports.ESPN2,
	"ESPN3":                 dbSports.ESPN3,
	"ESPNU":                 dbSports.ESPNU,
	"FACEBOOK":              dbSports.Facebook,
	"FloSports":             dbSports.FloSports,
	"Fox Sports 1":          dbSports.FS1,
	"Fox Sports 2":          dbSports.FS2,
	"FOX":                   dbSports.FOX,
	"HBCUGo":                dbSports.HBCUGo,
	"HNIC":                  dbSports.HNIC,
	"KCOP-TV":               dbSports.KCOPTV,
	"KENS":                  dbSports.KENS,
	"KONG":                  dbSports.KONG,
	"KTLA":                  dbSports.KTLA,
	"KTNV":                  dbSports.KTNV,
	"KTXA":                  dbSports.KTXA,
	"LHN":                   dbSports.LHN,
	"MARQ":                  dbSports.MARQ,
	"Marquee Sports":        dbSports.MARQ,
	"MASN":                  dbSports.MASN,
	"MASN2":                 dbSports.MASN2,
	"Midco Sports":          dbSports.MidcoSports,
	"MLB Network":           dbSports.MLBN,
	"MSG":                   dbSports.MSG,
	"MSG-B":                 dbSports.MSGB,
	"MSG+":                  dbSports.MSGPlus,
	"MSGSN":                 dbSports.MSGSN,
	"MSGSN2":                dbSports.MSGSN2,
	"MSG2":                  dbSports.MSG2,
	"MSG 2":                 dbSports.MSG2,
	"MSG+ 2":                dbSports.MSGPlus2,
	"MW Network":            dbSports.MWNetwork,
	"NBA TV":                dbSports.NBA_TV,
	"NBC 10":                dbSports.NBC_WCAU,
	"NBC":                   dbSports.NBC,
	"NBCS-BA":               dbSports.NBCSBA,
	"NBCS-BOS":              dbSports.NBCSBOS,
	"NBCS-CA":               dbSports.NBCSCA,
	"NBCS-CA+":              dbSports.NBCSCAPlus,
	"NBCS-CHI":              dbSports.NBCSCHI,
	"NBCS-CHI+":             dbSports.NBCSCHIPlus,
	"NBCS-DC":               dbSports.NBCSDC,
	"NBCS-DC+":              dbSports.NBCSDCPlus,
	"NBCS-PH":               dbSports.NBCSPH,
	"NBCS-PH+":              dbSports.NBCSPHPlus,
	"NEC Front Row":         dbSports.NECFrontRow,
	"NESN":                  dbSports.NESN,
	"NESN+":                 dbSports.NESNPlus,
	"NFL Network":           dbSports.NFLNetwork,
	"NHL Network":           dbSports.NHLNetwork,
	"Pac-12 Network":        dbSports.Pac12Network,
	"Pac-12 Now":            dbSports.Pac12Now,
	"Peacock":               dbSports.Peacock,
	"Prime Video":           dbSports.PrimeVideo,
	"RDS":                   dbSports.RDS,
	"RDS2":                  dbSports.RDS2,
	"RSDI":                  dbSports.RDSI,
	"ROOT Sports NW":        dbSports.ROOTSportsNW,
	"ROOT Sports NW+":       dbSports.ROOTSportsNWPlus,
	"RSN":                   dbSports.ACC_RSN,
	"SEC Network":           dbSports.SECNetwork,
	"SEC Network+":          dbSports.SECNetworkPlus,
	"SN1":                   dbSports.SN1,
	"SNET":                  dbSports.SNET,
	"Sportsnet":             dbSports.SNET,
	"SportsNet":             dbSports.SNET,
	"SNP":                   dbSports.SNP,
	"SN360":                 dbSports.SN360,
	"SNE":                   dbSports.SNE,
	"SNF":                   dbSports.SNF,
	"SNO":                   dbSports.SNO,
	"SNOL":                  dbSports.SNOL,
	"SNY":                   dbSports.SNY,
	"SNW":                   dbSports.SNW,
	"Spectrum Sports":       dbSports.SpectrumSports,
	"SportsNet LA":          dbSports.SportsNetLA,
	"SportsNet PT":          dbSports.SportsNetPT,
	"SportsNet RM":          dbSports.SportsNetRM,
	"SportsNet SW":          dbSports.SportsNetSW,
	"STADIUM":               dbSports.Stadium,
	"TBS":                   dbSports.TBS,
	"TNT":                   dbSports.TNT,
	"TSN":                   dbSports.TSN,
	"TSN2":                  dbSports.TSN2,
	"TSN3":                  dbSports.TSN3,
	"TSN4":                  dbSports.TSN4,
	"TSN5":                  dbSports.TSN5,
	"TVAS":                  dbSports.TVAS,
	"TVAS2":                 dbSports.TVAS2,
	"USA":                   dbSports.USA,
	"WCC Network":           dbSports.WCCNetwork,
	"WPIX":                  dbSports.WPIX,
	"WVUE":                  dbSports.WVUE,
	"YES":                   dbSports.YES,
	"YES App":               dbSports.YESApp,
	"YouTube":               dbSports.YouTube,
}
